/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AApp: typeof import('ant-design-vue/es')['App']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputGroup: typeof import('ant-design-vue/es')['InputGroup']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AppBreadcrumb: typeof import('./src/components/navigation/AppBreadcrumb.vue')['default']
    AppMenuTabs: typeof import('./src/components/navigation/AppMenuTabs.vue')['default']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    CaptchaInput: typeof import('./src/components/common/CaptchaInput.vue')['default']
    IconPicker: typeof import('./src/components/IconPicker.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSettings: typeof import('./src/components/ThemeSettings.vue')['default']
  }
}
